from pathlib import Path

path = Path("scripts/apply-m4-slice5.py")
text = path.read_text()

readme_old = '''replace_once(\n    "README.md",\n    "M4 is the selected next milestone. Slices 1 to 4 add typed loop success conditions, structured iteration-region validation, schema version 3, deterministic feedback continuation, isolated multi-iteration task and check loops, failed check observations, and hard iteration limits. Later slices add progress and patience rules, recovery hardening, and the complete Pi loop surface. M3.1 parser adapters are deferred until after v0.5.",\n    "M4 is the selected next milestone. Slices 1 to 5 add typed loop success conditions, structured iteration-region validation, deterministic feedback continuation, check-driven repair loops, hard iteration limits, numeric progress metrics, best-result tracking, and patience failure. Later slices add recovery hardening and the complete Pi loop surface. M3.1 parser adapters are deferred until after v0.5.",\n)'''
readme_new = '''replace_once(\n    "README.md",\n    "M4 is in progress. It extends executable bounded loops with multi-iteration repair behavior, progress rules, recovery hardening, and the complete Pi loop surface.",\n    "M4 is in progress. Slices 1 to 5 provide multi-iteration task and check repair loops, hard iteration limits, numeric progress metrics, best-result tracking, and patience failure. Later slices add recovery hardening and the complete Pi loop surface.",\n)'''

skill_old = '''replace_once(\n    "skills/hypagraph/SKILL.md",\n    "M4 Slices 1 to 4 execute task-based and command-check repair loops across isolated iterations. A failed evaluation check can continue the loop only when the raw result status is `failed`, normalization succeeded, and all required facts were published. Cancellation, interruption, timeout, executor error, or a failed non-evaluation check does not continue automatically. A check retry stays in the current iteration. A loop continuation creates a new iteration and a new attempt ID. The final unsuccessful allowed iteration fails the loop and workflow with `max_iterations`. Do not select a feedback route manually. Patience is not active yet.",\n    "M4 Slices 1 to 5 execute bounded task-based and command-check repair loops. Optional progress uses one numeric fact with a minimize or maximize direction. Improvement must exceed `minDelta`; equal values do not improve. Hypagraph records the best metric, best iteration, and no-progress count. Patience can fail the loop with `no_progress`, but a successful evaluator completes first and the hard iteration limit has priority over patience. Missing or invalid progress data fails with `evaluation_error`. Do not select loop decisions manually.",\n)'''
skill_new = '''replace_once(\n    "skills/hypagraph/SKILL.md",\n    "M4 Slices 1 to 4 execute bounded task-based and command-check repair loops across isolated iterations. A failed evaluation check can continue the loop only when the raw result status is `failed`, normalization succeeded, and all required facts were published. Cancellation, interruption, timeout, executor error, or a failed non-evaluation check does not continue automatically. A check retry stays in the current iteration. A loop continuation creates a new iteration and a new attempt ID. Do not select a feedback route manually. The final unsuccessful iteration records `max_iterations`, fails the loop, and fails the workflow. Patience is not active yet.",\n    "M4 Slices 1 to 5 execute bounded task-based and command-check repair loops. Optional progress uses one numeric fact with a minimize or maximize direction. Improvement must exceed `minDelta`; equal values do not improve. Hypagraph records the best metric, best iteration, and no-progress count. Patience can fail the loop with `no_progress`, but a successful evaluator completes first and the hard iteration limit has priority over patience. Missing or invalid progress data fails with `evaluation_error`. Do not select loop decisions manually.",\n)'''

docs_old = """replace_once(\n    \"docs/event-runtime.md\",\n    '''M4 Slices 1 to 4 support successful task and check iterations, deterministic feedback continuation, isolated iteration reset, failed evaluation-check observations, and hard iteration limits.\n\nIt does not yet support:\n\n- progress metrics or patience;\n''',\n    '''M4 Slices 1 to 5 support successful task and check iterations, deterministic feedback continuation, isolated iteration reset, failed evaluation-check observations, hard iteration limits, numeric progress metrics, best-result tracking, and patience failure.\n\nProgress decisions are stored in `hypagraph.loop.evaluated`. The event contains the metric, improvement result, best metric, best iteration, and no-progress count. Replay does not recalculate them. A missing or invalid current-iteration metric fails the loop with `evaluation_error`. Hard-limit failure has priority over patience failure.\n\nIt does not yet support:\n\n''',\n)"""
docs_new = """replace_once(\n    \"docs/event-runtime.md\",\n    '''M4 Slices 1 to 4 support successful task and check iterations, deterministic feedback continuation, isolated iteration reset, failed evaluation-check observations, and hard-limit failure.\n\nIt does not yet support:\n\n- progress metrics or patience;\n''',\n    '''M4 Slices 1 to 5 support successful task and check iterations, deterministic feedback continuation, isolated iteration reset, failed evaluation-check observations, hard iteration limits, numeric progress metrics, best-result tracking, and patience failure.\n\nProgress decisions are stored in `hypagraph.loop.evaluated`. The event contains the metric, improvement result, best metric, best iteration, and no-progress count. Replay does not recalculate them. A missing or invalid current-iteration metric fails the loop with `evaluation_error`. Hard-limit failure has priority over patience failure.\n\nIt does not yet support:\n\n''',\n)"""

for old, new, name in ((readme_old, readme_new, "README"), (skill_old, skill_new, "skill"), (docs_old, docs_new, "runtime documentation")):
    if old not in text:
        raise SystemExit(f"The Slice 5 {name} migration block was not found.")
    text = text.replace(old, new, 1)

path.write_text(text)
